atari:
  - Pong:
      envname: PongNoFrameskip-v4
      env:
        seed: 750
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1150
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - SpaceInvaders:
      envname: SpaceInvadersNoFrameskip-v4
      env:
        seed: 750
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1150
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - Breakout:
      envname: BreakoutNoFrameskip-v4
      env:
        seed: 750
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1150
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000
  - Pong:
      envname: PongNoFrameskip-v4
      env:
        seed: 745
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1249
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - SpaceInvaders:
      envname: SpaceInvadersNoFrameskip-v4
      env:
        seed: 745
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1249
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - Breakout:
      envname: BreakoutNoFrameskip-v4
      env:
        seed: 745
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1249
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - Pong:
      envname: PongNoFrameskip-v4
      env:
        seed: 450
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1450
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - SpaceInvaders:
      envname: SpaceInvadersNoFrameskip-v4
      env:
        seed: 450
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1450
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000

  - Breakout:
      envname: BreakoutNoFrameskip-v4
      env:
        seed: 450
        n_envs: 16
      framestack:
        n_stack: 4
      agent:
        seed: 1450
        policy: 'CnnPolicy'
        learning_rate: 0.007
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1
        ent_coef: 0.01
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 0.00001
      learn:
        total_timesteps: !!float 1e7
        log_interval: 5000