from stable_baselines3.envs.DefeatZerglingsAndBanelings import DZBEnv
from stable_baselines3.envs.DefeatRoaches import DREnv
from stable_baselines3.envs.CollectMineralAndGas import CMGEnv
from stable_baselines3.envs.CollectMineralShards import CMSEnv
from stable_baselines3.envs.FindAndDefeatZerglings import FDZEnv
from stable_baselines3.envs.MoveToBeacon import MTBEnv
from stable_baselines3.envs.BuildMarines import BMEnv
